#!/usr/bin/perl

use strict;
use NethServer::Service;
use esmith::util;

# initialize mysql installation

my $passwd_file = "/etc/my.pwd";
my $backup_dir="/var/lib/nethserver/backup/rh-mysql56/";
my $password = esmith::util::genRandomPassword($passwd_file);

## load existing dumps 
if ( -f "$backup_dir/mysql.dump" ) {
    system("/etc/e-smith/events/actions/rh-mysql56-load-tables");
} else { # or initialize the server
system("/sbin/service rh-mysql56-mysqld start");
system("/sbin/service rh-mysql56-mysqld stop");
system("/opt/rh/rh-mysql56/root/usr/libexec/mysqld --datadir=/var/opt/rh/rh-mysql56/lib/mysql --bootstrap --user=mysql --skip-grant-tables --explicit_defaults_for_timestamp < /opt/rh/rh-mysql56/root/bin/set.password");
    }
